services:
  app:
    image: codemelia/laps:v3
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-lapsdb}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: